function createfigure(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 07-Dec-2015 20:42:45

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(Y1,'Color',[1 0 0]);

% Create xlabel
xlabel({'Iteration'},'FontSize',11);

% Create ylabel
ylabel({'MSE'},'FontSize',11);

% Create title
title({'Batche MSE'},'FontSize',11);

