function createfigure(YMatrix1, YMatrix2,YMatrix3)
%CREATEFIGURE(YMATRIX1, YMATRIX2)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 19-Jan-2016 22:29:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Accuracy Train');
set(plot1(2),'DisplayName','Accuracy Test');
set(plot1(3),'DisplayName','Accuracy Validation');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',axes1);
set(plot2(1),'DisplayName','Accuracy_Test');
set(plot2(2),'DisplayName','Accuracy_Train');
set(plot2(3),'DisplayName','Accuracy_Validation');

% Create multiple lines using matrix input to plot
plot3 = plot(YMatrix3,'Parent',axes1);
set(plot2(1),'DisplayName','Accuracy_Test');
set(plot2(2),'DisplayName','Accuracy_Train');
set(plot2(3),'DisplayName','Accuracy_Validation');


box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.173600794818507 0.295336790035421 0.120356609837261 0.0944156567118397]);

