function draw_MSE(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 31-Jan-2016 12:49:57

% Create figure
figure10 = figure;

% Create axes
axes1 = axes('Parent',figure10);
hold(axes1,'on');

% Create plot
plot(Y1,'DisplayName','MSE','LineWidth',3,'LineStyle','-.',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);

% Create xlabel
xlabel({'Epoch'});

% Create ylabel
ylabel({'MSE'});

% Create title
title({'MSE'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.83064909779688 0.864833913969659 0.0636896040088785 0.0366552110936359]);

